name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ${{ matrix.locale }}
        env:
          # US credentials
          US_USERNAME: ${{ secrets.US_USERNAME }}
          US_PASSWORD: ${{ secrets.US_PASSWORD }}
          # UK credentials
          UK_USERNAME: ${{ secrets.UK_USERNAME }}
          UK_PASSWORD: ${{ secrets.UK_PASSWORD }}
          # Germany credentials
          DE_USERNAME: ${{ secrets.DE_USERNAME }}
          DE_PASSWORD: ${{ secrets.DE_PASSWORD }}
          # France credentials
          FR_USERNAME: ${{ secrets.FR_USERNAME }}
          FR_PASSWORD: ${{ secrets.FR_PASSWORD }}
          # Japan credentials
          JP_USERNAME: ${{ secrets.JP_USERNAME }}
          JP_PASSWORD: ${{ secrets.JP_PASSWORD }}
          # Australia credentials
          AU_USERNAME: ${{ secrets.AU_USERNAME }}
          AU_PASSWORD: ${{ secrets.AU_PASSWORD }}
          # Brazil credentials
          BR_USERNAME: ${{ secrets.BR_USERNAME }}
          BR_PASSWORD: ${{ secrets.BR_PASSWORD }}
          # India credentials
          IN_USERNAME: ${{ secrets.IN_USERNAME }}
          IN_PASSWORD: ${{ secrets.IN_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.locale }}
          path: playwright-report/
          retention-days: 30
